name: Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  changelog:
    name: Changelog
    permissions:
      contents: write
    uses: mozex/reusable-workflows/.github/workflows/changelog.yml@0cbd7ab3ff42b431460c2438badd2a077ed58222 # main
